1hw create Process class
axel36/sphere_cpp_2020 pull request #1
Opened 2020-10-04 17:07 UTC by axel36

2020-10-04 22:36 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +    return;
Не понимаю, что произойдет в форке при неправильной работе execlp - исполнение выйдет из конструктора и продолжится в дочернем процессе?

2020-10-08 17:26 UTC, Kapitonov requested changes

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +  return ::read(read_from_child_fd, data, len);
Когда ::read вернет ошибку, вы вернете большое число при касте знакового к безнаковому. Это может вызвать различные ошибки. Надо проверять что вернул read в случае ошибки сообщать об этом и завершать программу.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +  } else {
Кастить беззнаковый 8байтный тип в знаковому 4байтному типу не лучшая практика. Лучше использовать size_t bytes_read.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +  int rest = len;
Зачем интовая переменная? Если мы ожидаем большое количество данных, то rest может стать отрицательным  или положительным, но меньшим чем len, поскольку будет выполнено сужающее преобразование.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +    if (isChannelOpen()) {
Не закрываете read_from_child_fd.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +  fork_pid_ = fork();
Нет проверки на то, что fork выполнился корректно.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/include/Process.hpp
> +  int read_from_child_fd = -1;
У следующих переменных есть суффикс _ значит и тут надо добавить.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/include/Process.hpp
> +  inline bool isChannelOpen() const { return channel_open_; }
Возможно их тоже стоит вынести в cpp.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/include/Process.hpp
> +  bool channel_open_ = true;
Лучше ставить в невалидное состояние fork_pid_ при уничтожении процесса и проверять её валидность, тогда этот флаг будет не нужен.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/include/Process.hpp
> +  bool process_running_ = true;
Анадогично можно делать невалидной переменную файлового дескриптора и проверять её валидность вместо флага.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +  int rest = len;
Снова size_t->int

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +    position += bytes_read;
При переполнении position может стать отрицательным, тогда мы получим проблемы.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +  int bytes_write = -1;
При кате size_t -> int bytes_write может стать о трицательным, что приведет к исключению  при правильно работающей программе. Не используйте int, поскольку ваш метод не может вернуть отрицательное значение.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +    position += bytes_write;
Аналогично readExact

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +    return;
Да, ровно так и произойдет.

2020-10-08 17:26 UTC, Kapitonov commented on lib/hw_1_process/CMakeLists.txt
> +add_library(hw_1_process SHARED src/Process.cpp)
Возможно, лучше в данном случае сделать статичную библиотеку.

2020-10-08 17:26 UTC, Kapitonov commented on lib/CMakeLists.txt
> +
Лишние строки

2020-10-08 23:20 UTC, axel36 commented on lib/hw_1_process/include/Process.hpp
> +  int read_from_child_fd = -1;
поправил

2020-10-08 23:20 UTC, axel36 commented on lib/hw_1_process/include/Process.hpp
> +  inline bool isChannelOpen() const { return channel_open_; }
поправил

2020-10-08 23:49 UTC, axel36 commented on lib/hw_1_process/include/Process.hpp
> +  bool channel_open_ = true;
поправил

2020-10-08 23:49 UTC, axel36 commented on lib/hw_1_process/include/Process.hpp
> +  bool process_running_ = true;
поправил

2020-10-08 23:49 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +  int rest = len;
поправил

2020-10-08 23:55 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +    position += bytes_read;
Ну, строго говоря - я не знаю, как тут может возникнуть переполнение: 
`position` всегда меньше, чем `len`, и как только оно могло бы переполнится - исполнение сюда не дойдет, мы войдем в if

2020-10-08 23:56 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +  int bytes_write = -1;
поправил

2020-10-08 23:57 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +    position += bytes_write;
поправил

2020-10-08 23:58 UTC, axel36 commented on lib/hw_1_process/CMakeLists.txt
> +add_library(hw_1_process SHARED src/Process.cpp)
А почему?

2020-10-08 23:58 UTC, axel36 commented on lib/CMakeLists.txt
> +
поправил

2020-10-08 23:58 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +  fork_pid_ = fork();
поправил

2020-10-09 00:06 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +    if (isChannelOpen()) {
я думал, что у пайпа есть некий буффер и, что это валидная ситуация, когда мы решили закончить выполнение процесса но не дочитали все из пайпа и потом захотим прочитать из завершившегося процесса.

В общем, поправил

2020-10-09 00:08 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +  int rest = len;
Я что-то тупанул, и не обратил внимания, что у нас read возвращает size_t и вообще везде size_t...
поправил

2020-10-09 00:09 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +  } else {
поправил

2020-10-09 00:09 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +  return ::read(read_from_child_fd, data, len);
Я что-то тупанул, и не обратил внимания, что у нас read возвращает size_t и из-за этого все остальное написал так, как будто read возвращает int...
вроде все исправил

2020-10-09 00:12 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +    return;
Тогда это ок убивать самого себя через `raise(SIGINT);` ?
как-то можно просигнализировать из дочернего процесса, что тут проблема?
или нам waitpid вернет -1, если тут вызовем SIGINT?

2020-10-09 00:24 UTC, Kapitonov commented on lib/hw_1_process/CMakeLists.txt
> +add_library(hw_1_process SHARED src/Process.cpp)
На мой взгляд. Если библиотека динамическая, то нам надо с собой таскать so файл этой библиотеки вместе с бинарником. Особых плюсов на маленьких библиотеках мы не получим.

2020-10-09 00:42 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +    return;
Насчет просигнализировать, на лекции был пример, как дожидаться вызова execlp  с помошью pipe с флагом O_CLOEXEC. Убить себя можно, например exit(1). Но желательно как-то сообщить о причине смерти, выведя что-то в поток ошибок или вообще бросить исключение.

2020-10-09 08:24 UTC, Kapitonov commented on lib/hw_1_process/src/Process.cpp
> +    return;
Вообще, сейчас не сильно критично проверять прошел ли exec.

2020-10-09 09:58 UTC, axel36 commented on lib/hw_1_process/src/Process.cpp
> +    return;
А как это вообще устроенно: если я в соседнем процессе кидаю исключение, оно же пойдет обрабатываться(или не обрабатываться) в соседнем процессе, мой процесс об этом даже не узнает ничего, или узнает и тоже завершится?

2020-10-09 10:37 UTC, axel36 commented on lib/hw_1_process/CMakeLists.txt
> +add_library(hw_1_process SHARED src/Process.cpp)
поменял

2020-10-09 15:55 UTC, axel36 commented on lib/hw_1_process/include/Process.hpp
> +  inline bool isChannelOpen() const { return channel_open_; }
Как я понял inline функции следует определять в hpp, вернул назал

2020-10-11 20:56 UTC, axel36 commented on lib/hw_1_process/include/Process.hpp
> +  inline bool isChannelOpen() const { return channel_open_; }
убрал

2020-10-14 14:36 UTC, Kapitonov requested changes

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/include/process.hpp
> +#include "descriptor.hpp"
Если делаете после прагмы пустую строку, то надо делать везде.

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/include/descriptor.hpp
> +  ~Descriptor() noexcept;
Он изначально предполагается как noexcept

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/descriptor.cpp
> +  } catch (const DescriptorError &) {
Давайте напишем что это за ошибка в поток ошибок?

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/descriptor.cpp
> +void Descriptor::close() {
Почему в методе closeThrow есть проверка, а тут нет?

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/include/process.hpp
> +  explicit ProcessError(const std::string &msg) : std::runtime_error(msg) {}
Лучше через using

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/descriptor.cpp
> +    if (isValid()) {
у вас есть метод close, который по смыслу именно это и должен делать.

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/descriptor.cpp
> +    fd_ = other.fd_;
ЕКсли использовать метод close, то потом можно использовать swap.

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/descriptor.cpp
> +  } catch (const std::exception &exc) {
Если исключение кидали не вы, то возможно лучше упасть.

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/process.cpp
> +#include <zconf.h>
А точно надо?

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/process.cpp
> +    to_parent_write.close();
Зачем закрывать руками, если их деструктор это сделает?

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/process.cpp
> +  } catch (const std::exception &exc) {
Вы уверены, что стоит ловить исключения кторые породили не вы?

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/process.cpp
> +Process::~Process() {
Достаточно послать сигнал процессу и дождаться его завершения, дескрипторы бы закрылись в своих деструкторах.

2020-10-14 14:36 UTC, Kapitonov commented on lib/hw_1_process/src/descriptor.cpp
> +bool Descriptor::isValid() const { return fd_ > 0; }
0 это валидное значение файлового дескриптора.

2020-10-14 15:06 UTC, axel36 commented on lib/hw_1_process/src/descriptor.cpp
> +void Descriptor::close() {
Мне было удобно в классе process делать логику 
```
if(descriptor.valid()){
descriptor.close()
}
```
иначе получалось, что я делаю два одинаковых if подряд

и я подумал, что это удобно - сделать два метода, один внутри себя проверяет валидность второй нет, но может закрыть невалидный дескриптор и словить что-то неприятное, 

я хотел сделать что-то похожее на [] и at() у вектора

2020-10-14 15:08 UTC, axel36 commented on lib/hw_1_process/src/descriptor.cpp
> +    if (isValid()) {
Да, но в методе close мне крайне необходимо выставлять значение fd_ = -1, а тут не обязательно, и я решил, что лучше не делать лишних присваиваний

2020-10-14 15:09 UTC, axel36 commented on lib/hw_1_process/src/descriptor.cpp
> +    fd_ = other.fd_;
О, круто, не подумал об этом

2020-10-14 15:11 UTC, axel36 commented on lib/hw_1_process/src/descriptor.cpp
> +    fd_ = other.fd_;
Но я правильно понимаю, что особой выгоды или еще чего-нибудь это не даст?

2020-10-14 15:11 UTC, axel36 commented on lib/hw_1_process/src/descriptor.cpp
> +  } catch (const std::exception &exc) {
Хммм, но это же деструктор?

2020-10-16 15:55 UTC, axel36 commented on lib/hw_1_process/src/descriptor.cpp
> +bool Descriptor::isValid() const { return fd_ > 0; }
поправил

2020-10-16 15:55 UTC, axel36 commented on lib/hw_1_process/src/process.cpp
> +Process::~Process() {
поправил

2020-10-16 15:55 UTC, axel36 commented on lib/hw_1_process/src/process.cpp
> +  } catch (const std::exception &exc) {
поправил

2020-10-16 15:57 UTC, axel36 commented on lib/hw_1_process/src/process.cpp
> +    to_parent_write.close();
А в момент вызова execlp вызовется деструктор всего, что было у нас на стеке?

2020-10-16 15:58 UTC, axel36 commented on lib/hw_1_process/src/process.cpp
> +#include <zconf.h>
без него не компилится у меня(

2020-10-16 16:18 UTC, axel36 commented on lib/hw_1_process/include/process.hpp
> +  explicit ProcessError(const std::string &msg) : std::runtime_error(msg) {}
поправил

2020-10-16 17:45 UTC, axel36 commented on lib/hw_1_process/src/descriptor.cpp
> +  } catch (const DescriptorError &) {
вообще убрал это исключение

2020-10-16 17:46 UTC, axel36 commented on lib/hw_1_process/include/process.hpp
> +#include "descriptor.hpp"
поправил

2020-10-19 05:28 UTC, Kapitonov requested changes

2020-10-19 05:28 UTC, Kapitonov commented on lib/hw_1_process/CMakeLists.txt
> +add_library(hw_1_descriptor STATIC src/descriptor.cpp include/descriptor.hpp)
Добавлять заголовочные файлы не надо.

2020-10-19 05:28 UTC, Kapitonov commented on lib/hw_1_process/src/process.cpp
> +#include <zconf.h>
unistd.h, если я правильно понимаю вашу проблему с close/

2020-10-19 05:28 UTC, Kapitonov commented on lib/hw_1_process/src/process.cpp
> +    to_parent_write.close();
Давайте оставим как есть.

2020-10-19 15:28 UTC, axel36 commented on lib/hw_1_process/CMakeLists.txt
> +add_library(hw_1_descriptor STATIC src/descriptor.cpp include/descriptor.hpp)
убрал

2020-10-19 15:30 UTC, axel36 commented on lib/hw_1_process/src/process.cpp
> +#include <zconf.h>
Поправил

2020-10-21 02:36 UTC, Kapitonov requested changes
После исправления влейте в мастер сами.

2020-10-21 02:36 UTC, Kapitonov commented on lib/hw_1_process/src/descriptor.cpp
> +#include <zconf.h>
Замените этот файл.

2020-10-21 10:52 UTC, merged