feat 2hw: add logger
axel36/sphere_cpp_2020 pull request #2
Opened 2020-10-16 14:58 UTC by axel36

2020-10-16 19:44 UTC, a-badin requested changes

2020-10-16 19:44 UTC, a-badin commented on lib/hw_2_logger/CMakeLists.txt
> +add_executable(test_hw_2 tests/main_test.cpp src/logger.cpp src/stdout_logger.cpp src/stderr_logger.cpp src/file_logger.cpp)
target_link_library(

2020-10-16 19:44 UTC, a-badin commented on lib/hw_2_logger/src/logger.cpp
> +std::string LevelToString(const Level &level) {
static 
или 
namespace {

}

2020-10-16 19:44 UTC, a-badin commented on lib/hw_2_logger/src/logger.cpp
> +void BaseLogger::SetLevel(const Level &level) { level_ = level; }
Level по значению

2020-10-16 19:44 UTC, a-badin commented on lib/hw_2_logger/include/logger.hpp
> +  virtual void Log(const Level &level, const std::string &msg);
virtual ~BaseLogger() = default;

2020-10-16 19:44 UTC, a-badin commented on lib/hw_2_logger/include/logger.hpp
> +  virtual void Error(const std::string &msg);
не нужно

2020-10-16 19:44 UTC, a-badin commented on lib/hw_2_logger/include/logger.hpp
> +  virtual void PrintLog(const Level &level, const std::string &msg) {}
= 0;

2020-10-16 19:44 UTC, a-badin commented on lib/hw_2_logger/include/logger.hpp
> +  virtual void Flush() {}
= 0;

2020-10-16 19:44 UTC, a-badin commented on lib/hw_2_logger/tests/main_test.cpp
> +  const auto logger1 = std::make_unique<log::StderrLogger>();
std::unique_ptr<log::BaseLogger>

2020-10-16 19:44 UTC, a-badin commented on lib/hw_2_logger/src/file_logger.cpp
> +FileLogger::~FileLogger() { log_file_.close(); }
log_file_.flush()

2020-10-17 00:29 UTC, axel36 commented on lib/hw_2_logger/CMakeLists.txt
> +add_executable(test_hw_2 tests/main_test.cpp src/logger.cpp src/stdout_logger.cpp src/stderr_logger.cpp src/file_logger.cpp)
поправил

2020-10-17 00:29 UTC, axel36 commented on lib/hw_2_logger/src/logger.cpp
> +std::string LevelToString(const Level &level) {
поправил

2020-10-17 00:29 UTC, axel36 commented on lib/hw_2_logger/src/logger.cpp
> +void BaseLogger::SetLevel(const Level &level) { level_ = level; }
поправил

2020-10-17 00:29 UTC, axel36 commented on lib/hw_2_logger/include/logger.hpp
> +  virtual void Log(const Level &level, const std::string &msg);
ок, вроде понял

2020-10-17 00:29 UTC, axel36 commented on lib/hw_2_logger/include/logger.hpp
> +  virtual void Error(const std::string &msg);
поправил

2020-10-17 00:29 UTC, axel36 commented on lib/hw_2_logger/include/logger.hpp
> +  virtual void PrintLog(const Level &level, const std::string &msg) {}
поправил

2020-10-17 00:30 UTC, axel36 commented on lib/hw_2_logger/include/logger.hpp
> +  virtual void Flush() {}
поправил

2020-10-17 00:30 UTC, axel36 commented on lib/hw_2_logger/tests/main_test.cpp
> +  const auto logger1 = std::make_unique<log::StderrLogger>();
ок, вроде понял

2020-10-17 00:30 UTC, axel36 commented on lib/hw_2_logger/src/file_logger.cpp
> +FileLogger::~FileLogger() { log_file_.close(); }
поправил

2020-10-17 00:40 UTC, axel36 reviewed
Если честно, я сильно удивлен, что мой код работает...

2020-10-17 00:40 UTC, axel36 commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  return *global_logger_;
Я что-то совсем не понял - я правильно сделал?
Это ок, что я отдаю указатель на логгер, который потом кастуется в ссылку?

2020-10-17 00:40 UTC, axel36 commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  std::unique_ptr<BaseLogger> logger = std::make_unique<LoggerType>();
Это вообще ок, что я тут unique_ptr начал использовать и хранить?

2020-10-17 00:40 UTC, axel36 commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  static LoggerSingleton theSingleInstance;
и вот тут я правильно понимаю:
все статические переменные инициализируются до начала работы программы, так что этот объект создастся и удалится правильно
и при первом обращении к этой функции, theSingleInstance уже будет существовать и всегда будет отдаваться один и тот же?

2020-10-17 00:40 UTC, axel36 commented on lib/hw_2_logger/src/logger_singleton.cpp
> +    global_logger_ = std::make_unique<StdoutLogger>();
Стоит ли здесь так делать? или может стоит бросать исключение?

2020-10-18 11:33 UTC, a-badin requested changes

2020-10-18 11:33 UTC, a-badin commented on lib/hw_2_logger/src/file_logger.cpp
> +  if (!log_file_.is_open() || log_file_.bad()) {
кажется можно просто проверить `if(log_file)`

2020-10-18 11:33 UTC, a-badin commented on lib/hw_2_logger/include/logger.hpp
> +template <typename LoggerType> void init_with_logger_t(Level level);
Шаблон тут делает удобно только вам как реализатору, а тому кто будет пользоваться не очень. Потому что он не знает что передать в качестве LoggerType, он может вызывать init_with_logger_t<int>(),  init_with_logger_t<std::ostream>() и все что угодно. Ошибку он получит где-то внутри реализации, может даже очень глубоко внутри. Шаблоны удобны тогда, когда на на тип накладывается мало требований, например, копируемый или callable

2020-10-18 11:33 UTC, a-badin commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  static LoggerSingleton theSingleInstance;
Нет статическая переменная такого вида проиницилизируется когда первый раз код дойдет до этого места. Но преимущество этого подхода в отличии от , например, оябъвить static LoggerSingleton theSingleInstance; в теле класса. Что так если 2 потока дернут GetInstance() одновременно, вам компилятор гарантирует что theSingleInstance создаться 1 раз

2020-10-18 11:33 UTC, a-badin commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  std::unique_ptr<BaseLogger> logger = std::make_unique<LoggerType>();
Да, вместо std::unique_ptr<BaseLogger> можно поставить auto, так как тип вы уже указали в make_unique

2020-10-18 11:33 UTC, a-badin commented on lib/hw_2_logger/src/logger_singleton.cpp
> +template void init_with_logger_t<StderrLogger>(Level level);
что делает этот код

2020-10-18 11:33 UTC, a-badin commented on lib/hw_2_logger/src/logger_singleton.cpp
> +    global_logger_ = std::make_unique<StdoutLogger>();
Немного неожиданное поведение, а почему бы не сделать так, чтобы ситуация когда global_logger_ нулевой была невозможна

2020-10-18 11:33 UTC, a-badin commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  return *global_logger_;
Да, а как еще можно сделать?

2020-10-18 14:37 UTC, axel36 commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  return *global_logger_;
если честно, не знаю) но вы вроде говорили, что с сырыми указателями не очень хорошо работать

2020-10-18 14:38 UTC, axel36 commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  std::unique_ptr<BaseLogger> logger = std::make_unique<LoggerType>();
Вот этот момент я не понял - я хотел создавать тут указатель именно на базовый класс, а если я поставлю auto, то он же будет не базовым, а `std::unique_ptr<LoggerType>`, или нет?

2020-10-18 14:49 UTC, axel36 commented on lib/hw_2_logger/src/logger_singleton.cpp
> +template void init_with_logger_t<StderrLogger>(Level level);
таким образом я могу объявить шаблонную функцию в hpp файле, а определение написать в cpp,

 частичное определение шаблона, или как-то так, не знаю, [как правильно это называется)](https://isocpp.org/wiki/faq/templates#separate-template-fn-defn-from-decl)

2020-10-18 14:49 UTC, axel36 commented on lib/hw_2_logger/include/logger.hpp
> +template <typename LoggerType> void init_with_logger_t(Level level);
Хорошо, я скорее хотел поупрашняться в шаблонах

2020-10-18 15:04 UTC, axel36 commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  std::unique_ptr<BaseLogger> logger = std::make_unique<LoggerType>();
и еще не собирается с такой ошибкой на строчке, где вызывается SetGlobalLogger:

error: non-const lvalue reference to type 'unique_ptr<log::BaseLogger>' cannot bind to a value of unrelated type 'const unique_ptr<log::FileLogge>'

и это вроде логично, ведь SetGlobalLogger принимет - std::unique_ptr<BaseLogger> &logger

2020-10-18 20:11 UTC, axel36 commented on lib/hw_2_logger/src/logger_singleton.cpp
> +    global_logger_ = std::make_unique<StdoutLogger>();
при объявлении поля класса написать сделал:

  std::unique_ptr<BaseLogger> global_logger_ = std::make_unique<StdoutLogger>();

2020-10-18 20:13 UTC, axel36 commented on lib/hw_2_logger/src/file_logger.cpp
> +  if (!log_file_.is_open() || log_file_.bad()) {
поправил

2020-10-18 20:13 UTC, axel36 commented on lib/hw_2_logger/include/logger.hpp
> +template <typename LoggerType> void init_with_logger_t(Level level);
убрал шаблоны

2020-10-21 17:56 UTC, a-badin commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  std::unique_ptr<BaseLogger> logger = std::make_unique<LoggerType>();
Я тогда вам рекомендую принимать в SetGlobalLogger std::unique_ptr<BaseLogger> по значению. Я думал ссылки тоже молча преобразовываются. Плюсы этого подхода мы еще обсудим в начале след лекции

2020-10-21 18:01 UTC, a-badin requested changes

2020-10-21 18:01 UTC, a-badin commented on lib/hw_2_logger/src/logger_singleton.cpp
> +void LoggerSingleton::SetGlobalLogger(std::unique_ptr<BaseLogger> &logger) {
То что вы проинициализировали сразу синглтон логгером по-умолчанию еще не делает невозможным, когда global_logger_ указывает на null. Вам могут его передать здесь в качестве параметра

2020-11-19 09:31 UTC, a-badin approved these changes

2020-11-19 09:31 UTC, a-badin commented on lib/hw_2_logger/src/logger_singleton.cpp
> +  std::unique_ptr<BaseLogger> logger = std::make_unique<StderrLogger>();
допустимо писать auto logger = std::make_unique<StderrLogger>();, так как тип вы уже указали в `make_unique<StderrLogger>`

2020-11-19 09:32 UTC, a-badin commented
Засчитываю на 9

2020-11-19 09:32 UTC, merged